platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  use_frameworks!
  pod 'JWPlayerKit', '>= 4.0.0'
  pod 'GoogleAds-IMA-iOS-SDK', '~>3.14.1'
  pod 'google-cast-sdk'
  capacitor_pods
end

target 'PluginTests' do
  use_frameworks!
  pod 'JWPlayerKit', '>= 4.0.0'
  pod 'GoogleAds-IMA-iOS-SDK', '~>3.14.1'
  pod 'google-cast-sdk'
  capacitor_pods
end
